#!/bin/bash
# -----------------------------------------------------------------------------
# Run TUFLOW-FV (HD or AED WQ) on a single VM (GPU or OpenMP CPU; no SLURM).
# Features: env-overridable config, banner, 
# live heartbeat, captured log, exit-code check, structured health check, and
# formatted elapsed time. 
#
# Hardware (GPU vs CPU cores) is governed by the `hardware ==` flag inside the
# .fvc (default cpu). For CPU runs this script sets OMP_NUM_THREADS=$NCPU.
#
# Usage:
#   ./run_tuflowfv_vm.sh model_config.fvc
# Override config at invocation:
#   NCPU=32 ./run_tuflowfv_vm.sh model_config.fvc
#   HEARTBEAT_INTERVAL=30 ./run_tuflowfv_vm.sh model_config.fvc
# Background (survives disconnect):
#   nohup ./run_tuflowfv_vm.sh model_config.fvc > run.log 2>&1 &
#   tail -f run.log
# -----------------------------------------------------------------------------

set -uo pipefail   # NB: NOT -e — we capture the run's exit code ourselves.

# --- Configuration ----------------------------------------------------------
# WHICH AED WATER-QUALITY LIBRARY?  ***UNCOMMENT ONE OF THE TWO BELOW***
#
# TUFLOW-FV loads libtuflowfv_external_wq.so from LD_LIBRARY_PATH at startup,
# so the choice is made by which launcher you run — not by anything in the .fvc.
#
#   (a) SYSTEM  the stock launcher, using the AED library shipped with
#               TUFLOW-FV in /usr/local/lib/tuflowfv-2025.2  (v2.3.6)
#   (b) OWN     the wrapper generated by your own libaed-fv build; it puts
#               <build>/libaed-tfv first on LD_LIBRARY_PATH so your .so wins
#
# NB: both report a "2.x" version banner, so the banner CANNOT tell you which
# one loaded. To prove it, run:
#   LD_DEBUG=libs <launcher> your.fvc 2>&1 | grep -i external_wq
# and check the path on the "calling init:" line.

# --- (a) system default AED library ---
AED_LAUNCHER=/usr/local/bin/tuflowfv_2025.2

# --- (b) my own compiled AED library ---
#AED_LAUNCHER=/media/fileshare/AED/MATT/AED_Tools_Private/binaries/ubuntu/24.04/libaed_fv_latest/tuflowfv_libaed

# TUFLOW-FV launcher. On the Linux VM this is the `tuflowfv_2025.2` launcher
# script in /usr/local/bin (underscore) — it dispatches to the versioned build
# dir /usr/local/bin/tuflowfv-2025.2/ (hyphen) holding the exe + GPU kernels.
# On Windows it is assumed on PATH. Override with TUFLOWFV=/abs/path if needed.
if [[ "${OSTYPE:-}" == "msys" || "${OSTYPE:-}" == "win32" ]]; then
    TUFLOWFV=${TUFLOWFV:-tuflowfv_2025.2}
else
    TUFLOWFV=${TUFLOWFV:-$AED_LAUNCHER}
fi

# Human-readable label for the banner, derived from the launcher chosen above.
case "$TUFLOWFV" in
    *tuflowfv_libaed) WQ_DESC="own build — $(dirname "$TUFLOWFV")/libaed-tfv" ;;
    *)                WQ_DESC="system default — shipped with TUFLOW-FV 2025.2" ;;
esac

# OpenMP threads for CPU (hardware == cpu) runs. Ignored for GPU runs.
NCPU=${NCPU:-$(nproc 2>/dev/null || echo 8)}

# Heartbeat: every HEARTBEAT_INTERVAL seconds, print the latest model time,
# % complete and real:sim ratio parsed from the run log. Set HEARTBEAT_ON=0
# to disable.
HEARTBEAT_ON=${HEARTBEAT_ON:-1}
HEARTBEAT_INTERVAL=${HEARTBEAT_INTERVAL:-60}

# Banner machine/hardware readout. On Windows the machine-model lookup uses
# PowerShell (~0.3s); set MACHINE_INFO=0 to skip that one lookup for an instant banner.
MACHINE_INFO=${MACHINE_INFO:-1}

# Environment-variable repos ($ENV_REPO / $MODIFIER_REPO / $GIS_REPO).
# These matter ONLY if the .fvc (or its includes) actually reference them.
# Any repo var a .fvc references must resolve, or TUFLOW-FV will fail to open
# the referenced files; vars the .fvc does not use can stay "NOT SET".
# Exporting a var before invocation always overrides the default chosen here.
# ***SELECT/EDIT ONE OF THE OPTIONS BELOW (Windows path / Linux mount)***

# --- (a) not referenced by this .fvc ---
#ENV_REPO_DEFAULT=

# --- (b) forcing repo shared from another model tree ---
if [[ "${OSTYPE:-}" == "msys" || "${OSTYPE:-}" == "win32" ]]; then
    ENV_REPO_DEFAULT="G:/CSIEM/V1.7/MODEL/csiem_model_tfvaed_1.7/model_components/environment_repo"
else
    ENV_REPO_DEFAULT="/media/csiemcommon/CSIEM/V1.7/MODEL/csiem_model_tfvaed_1.7/model_components/environment_repo"
fi

export ENV_REPO="${ENV_REPO:-${ENV_REPO_DEFAULT:-NOT SET}}"
export MODIFIER_REPO="${MODIFIER_REPO:-NOT SET}"
export GIS_REPO="${GIS_REPO:-NOT SET}"

# Performance settings
ulimit -s unlimited 2>/dev/null || true
# ----------------------------------------------------------------------------

# --- Arguments & paths ------------------------------------------------------
FVC_FILE="${1:-}"
if [ -z "$FVC_FILE" ]; then
    echo "ERROR: no .fvc file specified"
    echo "Usage: ./run.sh <fvc_file>   (e.g. ./run.sh model_config.fvc)"
    exit 1
fi

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
cd "$SCRIPT_DIR"

if [ ! -f "$FVC_FILE" ]; then
    echo "❌ FVC file not found: $FVC_FILE"
    exit 1
fi

LOG_FILE="${FVC_FILE%.fvc}.log"

# --- Hardware: honour the .fvc `hardware ==` flag (default cpu) --------------
HARDWARE=$(grep -iE '^[[:space:]]*hardware[[:space:]]*==' "$FVC_FILE" 2>/dev/null \
    | head -1 | sed -E 's/.*==[[:space:]]*([A-Za-z]+).*/\1/' | tr '[:upper:]' '[:lower:]')
HARDWARE=${HARDWARE:-cpu}
if [ "$HARDWARE" = "cpu" ]; then
    export OMP_NUM_THREADS="$NCPU"
    HW_DESC="cpu — OMP_NUM_THREADS = $NCPU"
else
    export OMP_NUM_THREADS=1
    HW_DESC="$HARDWARE — GPU device set in .fvc"
fi

# --- Output directory: parsed from the .fvc `output dir ==` entry ------------
# (TUFLOW-FV's output location is dynamic)
OUT_DIR=$(grep -iE '^[[:space:]]*output dir[[:space:]]*==' "$FVC_FILE" 2>/dev/null \
    | head -1 | sed -E 's/.*==[[:space:]]*//' | tr -d '\r' | sed -E 's/[[:space:]]*$//')

# --- Date helper: "dd/mm/yyyy HH:MM:SS" -> epoch seconds (empty on failure) --
_to_epoch() {
    local s="$1" d t dd rest mm yyyy
    d="${s%% *}"; t="${s#* }"
    dd="${d%%/*}"; rest="${d#*/}"; mm="${rest%%/*}"; yyyy="${rest#*/}"
    date -d "${yyyy}-${mm}-${dd} ${t}" +%s 2>/dev/null
}

# --- Machine / hardware detection (portable: Linux + Windows Git Bash) -------
# Sets MACHINE_HOST, MACHINE_MODEL, CPU_MODEL, CPU_CORES, RAM_GB, GPU_INFO.
_detect_machine() {
    MACHINE_HOST=$(hostname 2>/dev/null)
    # CPU model — /proc works on Linux AND MSYS/Git Bash; env var as last resort
    CPU_MODEL=$(grep -m1 'model name' /proc/cpuinfo 2>/dev/null | sed -E 's/.*:[[:space:]]*//;s/[[:space:]]+$//')
    CPU_MODEL=${CPU_MODEL:-${PROCESSOR_IDENTIFIER:-unknown}}
    CPU_CORES=$(nproc 2>/dev/null || echo "${NUMBER_OF_PROCESSORS:-?}")
    RAM_GB=$(awk '/MemTotal/{printf "%.0f",$2/1048576}' /proc/meminfo 2>/dev/null)
    RAM_GB=${RAM_GB:-?}
    # System model / VM type — Linux DMI (instant), else PowerShell on Windows
    if [ -r /sys/devices/virtual/dmi/id/product_name ]; then
        MACHINE_MODEL=$(cat /sys/devices/virtual/dmi/id/product_name 2>/dev/null)
    elif [ "$MACHINE_INFO" = "1" ] && command -v powershell >/dev/null 2>&1; then
        MACHINE_MODEL=$(powershell -NoProfile -Command \
          '$c=Get-CimInstance Win32_ComputerSystem; "$($c.Manufacturer) $($c.Model)"' 2>/dev/null | tr -d '\r')
    fi
    MACHINE_MODEL=${MACHINE_MODEL:-unknown}
    # GPU — nvidia-smi works on Linux and Windows when drivers present
    GPU_INFO=$(nvidia-smi --query-gpu=name,memory.total --format=csv,noheader 2>/dev/null | head -1 | tr -d '\r')
    GPU_INFO=${GPU_INFO:-none detected}
}

# --- Heartbeat worker (prints latest progress every interval) ---------------
_heartbeat_loop() {
    while sleep "$HEARTBEAT_INTERVAL"; do
        ts="[$(date +%H:%M:%S)]"
        if [ ! -f "$LOG_FILE" ]; then
            printf '\r⏱️  %s waiting for %s...\033[K' "$ts" "$LOG_FILE"
            continue
        fi
        line=$(grep -hE '^t = ' "$LOG_FILE" 2>/dev/null | tail -1)
        if [ -z "$line" ]; then
            last=$(tail -1 "$LOG_FILE" 2>/dev/null | tr -s '[:space:]' ' ')
            printf '\r⏱️  %s %s\033[K' "$ts" "${last:-(initialising...)}"
            continue
        fi
        # Model time = text after 't = ' up to the first '.'
        mt=$(echo "$line" | sed -E 's/^t = ([0-9/]+ [0-9:]+).*/\1/')
        extra=""
        start_dt=$(grep -hE '^START TIME ==' "$LOG_FILE" 2>/dev/null | head -1 | sed -E 's/^START TIME ==[[:space:]]*//')
        end_dt=$(grep -hE '^END TIME ==' "$LOG_FILE" 2>/dev/null | head -1 | sed -E 's/^END TIME ==[[:space:]]*//')
        s0=$(_to_epoch "$start_dt"); s1=$(_to_epoch "$end_dt"); sc=$(_to_epoch "$mt")
        if [[ "$s0" =~ ^[0-9]+$ && "$s1" =~ ^[0-9]+$ && "$sc" =~ ^[0-9]+$ && "$s1" -gt "$s0" ]]; then
            adv=$(( sc - s0 )); tot=$(( s1 - s0 ))
            real=$(( $(date +%s) - start_time ))
            extra=$(awk -v a="$adv" -v t="$tot" -v r="$real" 'BEGIN{
                pct=100*a/t; days=a/86400;
                if (r>0) printf "  (%.0f%%, ~%.2f sim-days, 1:%.1f real:sim)", pct, days, a/r;
                else     printf "  (%.0f%%, ~%.2f sim-days)", pct, days; }')
        fi
        printf '\r⏱️  %s t = %s%s\033[K' "$ts" "$mt" "$extra"
    done
}

HEARTBEAT_PID=""
_cleanup_heartbeat() {
    if [ -n "$HEARTBEAT_PID" ]; then
        kill "$HEARTBEAT_PID" 2>/dev/null
        wait "$HEARTBEAT_PID" 2>/dev/null
        HEARTBEAT_PID=""
        printf '\n'   # fresh line after the overwriting heartbeat
    fi
}
trap _cleanup_heartbeat EXIT INT TERM

# --- Banner -----------------------------------------------------------------
start_time=$(date +%s)
_detect_machine
echo ""
echo "============================================================"
echo " TUFLOW-FV run: $FVC_FILE"
echo " $(date)"
echo "============================================================"
echo "  MACHINE    = $MACHINE_HOST ($MACHINE_MODEL)"
echo "  CPU        = $CPU_MODEL  [$CPU_CORES cores]"
echo "  MEMORY     = ${RAM_GB} GB"
echo "  GPU        = $GPU_INFO"
echo "  EXECUTABLE = $TUFLOWFV"
echo "  AED WQ LIB = $WQ_DESC"
echo "  HARDWARE   = $HW_DESC"
echo "  LOG        = $LOG_FILE"
echo "  OUTPUT     = ${OUT_DIR:-<not set in .fvc — see includes>}"
echo "  ENV_REPO   = $ENV_REPO"
echo "  MODIFIER   = $MODIFIER_REPO"
echo "  GIS_REPO   = $GIS_REPO"
echo "  (check files -> ./check/ ; model logs -> ./log/)"
echo "============================================================"

# --- Pre-flight -------------------------------------------------------------
# Repo-var sanity: warn if the .fvc (or its first-level includes) references a
# repo var that is NOT SET — TUFLOW-FV would fail to open those files.
inc_files=$(sed -nE 's/^[[:space:]]*include[[:space:]]*==[[:space:]]*([^!]*).*/\1/Ip' "$FVC_FILE" | tr -d '\r' | sed -E 's/[[:space:]]+$//')
for v in ENV_REPO MODIFIER_REPO GIS_REPO; do
    val=$(eval "echo \"\$$v\"")
    [ "$val" != "NOT SET" ] && continue
    if grep -Fq "\$$v" "$FVC_FILE" $inc_files 2>/dev/null; then
        echo "⚠️  \$$v is referenced by the .fvc (or its includes) but is NOT SET — export it before running."
    fi
done

if ! command -v "$TUFLOWFV" >/dev/null 2>&1 && [ ! -x "$TUFLOWFV" ]; then
    echo "❌ Cannot find TUFLOW-FV launcher '$TUFLOWFV'."
    echo "   Set TUFLOWFV=/abs/path, or check the launcher: ls -l /usr/local/bin/tuflowfv_2025.2"
    exit 1
fi

# Sanity: .fvc requests GPU but none was detected on this host
if [ "$HARDWARE" != "cpu" ] && [ "$GPU_INFO" = "none detected" ]; then
    echo "⚠️  .fvc requests 'hardware == $HARDWARE' but no GPU was detected (nvidia-smi found none)."
    echo "    The run may fail or fall back to CPU — verify the host, or set 'hardware == cpu' in the .fvc."
fi

# --- Run --------------------------------------------------------------------
echo ""
echo "Running TUFLOW-FV model..."
if [ "$HEARTBEAT_ON" = "1" ]; then
    echo "  Heartbeat prints every ${HEARTBEAT_INTERVAL}s."
    echo ""
    _heartbeat_loop &
    HEARTBEAT_PID=$!
fi

"$TUFLOWFV" "$FVC_FILE" > "$LOG_FILE" 2>&1
exit_code=$?

_cleanup_heartbeat

if [ $exit_code -ne 0 ]; then
    echo "❌ TUFLOW-FV run failed with exit code $exit_code."
    echo "------ ERROR LOG (tail) ------"
    tail -50 "$LOG_FILE"
else
    echo "✅ TUFLOW-FV run completed successfully."
fi

# Formatted elapsed
elapsed=$(( $(date +%s) - start_time ))
printf "⏱️ Time taken to run TUFLOW-FV: %02d:%02d:%02d (hh:mm:ss)\n" \
    $((elapsed/3600)) $(((elapsed%3600)/60)) $((elapsed%60))

# --- Run health check -------------------------------------------------------
# Surfaces warnings; does not override the run's exit code.
echo ""
echo "--- Run health check ---"
health_warn=0

if grep -q "Run Successful." "$LOG_FILE" 2>/dev/null; then
    echo "✅ log reports 'Run Successful.'"
else
    echo "❌ log does not contain 'Run Successful.' (run incomplete or aborted)"
    health_warn=1
fi

nwarn=$(grep -hE "Number of warnings =" "$LOG_FILE" 2>/dev/null | tail -1 | grep -oE '[0-9]+' | tail -1)
nwarn=${nwarn:-0}
if [ "$nwarn" -gt 0 ]; then
    echo "⚠️  TUFLOW-FV reported $nwarn warning(s) — see $LOG_FILE"
    health_warn=1
else
    echo "✅ no TUFLOW-FV warnings reported"
fi

nerr=$(grep -ciE "(^| )ERROR" "$LOG_FILE" 2>/dev/null)
if [ "${nerr:-0}" -gt 0 ]; then
    echo "⚠️  $nerr line(s) mention 'ERROR':"
    grep -niE "(^| )ERROR" "$LOG_FILE" 2>/dev/null | head -5 | sed 's/^/     /'
    health_warn=1
fi

# Final model time reached (last 't =' line)
last_t=$(grep -hE '^t = ' "$LOG_FILE" 2>/dev/null | tail -1 | sed -E 's/^t = ([0-9/]+ [0-9:]+).*/\1/')
[ -n "$last_t" ] && echo "ℹ️  final model time reached: $last_t"

# NetCDF output present? (OUT_DIR parsed from the .fvc near the top)
if [ -n "$OUT_DIR" ] && [ -d "$OUT_DIR" ]; then
    nc_count=$(ls "$OUT_DIR"/*.nc 2>/dev/null | wc -l)
    if [ "$nc_count" -gt 0 ]; then
        echo "✅ $nc_count NetCDF output file(s) in $OUT_DIR"
    else
        echo "⚠️  no .nc output files found in $OUT_DIR"
        health_warn=1
    fi
fi

if [ $health_warn -eq 0 ]; then
    echo "✅ All health checks passed — outputs look healthy."
else
    echo "⚠️  Health checks completed with warnings (see above)."
fi
echo ""

exit $exit_code
